---
- name: install {{package_name}} with default package manager
  action: "{{backcompat_pkg_mgr}} name={{package_name}}"
  sudo: yes
  when: backcompat_pkg_mgr == "yum" or backcompat_pkg_mgr == "apt"

# Handle dnf case for Fedora
- name: check if {{package_name}} exists
  command: rpm -q {{package_name}}
  changed_when: False
  ignore_errors: True
  register: package_exists_result
  when: backcompat_pkg_mgr == "dnf"

# Use command since dnf was only added as a module in ansible 1.9.0
- name: install {{package_name}} with dnf
  command: dnf install -y {{package_name}}
  sudo: yes
  when: backcompat_pkg_mgr == "dnf" and package_exists_result|failed
